### PR TITLE
Fixes system-incompatible paths in xml-report

### PR DESCRIPTION
**Pull request by ryskov**
Since forward-slashes are supported in Windows systems, there are really no reason not to replace backslashes with slashes in xml-reports.

### CODE REVIEW

**Comment by ryskov** [comment]
Fixes #1

**Comment by jaqra** [comment]
I so appreciate you to contribute this extension. Replace with system path separator (`path.sep`) would be better for consistency

**Comment by ryskov** [comment]
Good one! Just commited the change

**Comment by jaqra** [comment]
Thanks too much 🙂

**Pull request merged**
